docker volume create git
docker volume create vscode-server-deno-node
docker volume create vscode-server-dood-local
docker volume create vscode-server-go
docker volume create vscode-server-python
docker volume create vscode-server-rust
docker volume create deno
docker volume create npm
docker volume create go
docker volume create cargo
docker volume create rustup